import type { ContentStory } from './types';

export const SEED_STORIES: ContentStory[] = [
  {
    id: '5moAVDvB29vLOm5g4I9d',
    title: 'Satdham Vidyamandir Inauguration | Ahmedabad',
    slug: 'satdham-vidyamandir-inauguration-ahmedabad',
    showType: 'Social Events',
    shortDescription:
      'Flybit Dynamics brought the grand inauguration of Satdham Vidyamandir to life with a spectacular Drone Light Show, transforming the night sky into a captivating storytelling experience. Through synchronized aerial formations and precision choreography, the event left a lasting impression on students, parents, and guests.',
    content: `<h2>Event Highlights</h2>
<p>Flybit Dynamics brought the grand inauguration of Satdham Vidyamandir to life with a spectacular Drone Light Show, transforming the night sky into a captivating storytelling experience. Through synchronized aerial formations and precision choreography, the event left a lasting impression on students, parents, and guests.</p>`,
    thumbnailUrl: '/stories/satdham-vidyamandir-inauguration-ahmedabad/thumbnail.png',
    coverImageUrl: '/stories/satdham-vidyamandir-inauguration-ahmedabad/thumbnail.png',
    videoUrl: '/stories/Satdham Vidyamandir Inauguration/video.mp4',
    instagramUrl: '',
    metaTitle: 'Satdham Vidyamandir Inauguration Ahmedabad | FLYBIT Dynamics',
    metaDescription:
      'Grand inauguration of Satdham Vidyamandir in Ahmedabad with a spectacular drone light show by FLYBIT Dynamics.',
    seoKeywords: ['satdham vidyamandir', 'inauguration drone show', 'ahmedabad drone show'],
    tags: ['Social Events', 'Inauguration', 'Ahmedabad'],
    author: 'FLYBIT Team',
    readingTime: '4 min',
    featured: true,
    status: 'published',
    views: 1840,
    createdAt: '2025-03-15T10:00:00.000Z',
    updatedAt: '2025-03-15T10:00:00.000Z',
  },
  {
    id: 'QEy7ZR7rK1gQDS7g105G',
    title: "Govindpur's recognition as Ahmedabad's 25th Ward",
    slug: 'govindpurs-recognition-as-ahmedabads-25th-ward',
    showType: 'Social Events',
    shortDescription:
      "Flybit Dynamics celebrated Govindpur's recognition as Ahmedabad's 25th Ward with a breathtaking Drone Light Show, transforming the night sky into a canvas of aerial storytelling. The synchronized display created a memorable visual experience that united the community and marked this historic milestone.",
    content: `<h2>Historic Community Milestone</h2>
<p>Flybit Dynamics celebrated Govindpur's recognition as Ahmedabad's 25th Ward with a breathtaking Drone Light Show, transforming the night sky into a canvas of aerial storytelling. The synchronized display created a memorable visual experience that united the community and marked this historic milestone.</p>`,
    thumbnailUrl: '/stories/govindpurs-recognition-as-ahmedabads-25th-ward/thumbnail.png',
    coverImageUrl: '/stories/govindpurs-recognition-as-ahmedabads-25th-ward/thumbnail.png',
    videoUrl: "/stories/Govindpur's recognition as Ahmedabad's 25th Ward/video.mp4",
    instagramUrl: '',
    metaTitle: "Govindpur Ahmedabad 25th Ward Drone Show | FLYBIT Dynamics",
    metaDescription:
      "Celebrating Govindpur's recognition as Ahmedabad's 25th Ward with an aerial storytelling drone show.",
    seoKeywords: ['govindpur ahmedabad', '25th ward drone show', 'ahmedabad drone light show'],
    tags: ['Social Events', 'Community', 'Ahmedabad'],
    author: 'FLYBIT Team',
    readingTime: '4 min',
    featured: true,
    status: 'published',
    views: 2490,
    createdAt: '2025-01-26T10:00:00.000Z',
    updatedAt: '2025-01-26T10:00:00.000Z',
  },
  {
    id: '3fXIKCCdkWQLC4ZtpBCZ',
    title: 'science city drones show',
    slug: 'science-city-drones-show',
    showType: 'Government',
    shortDescription:
      'The skies above Ahmedabad Science City came alive with a spectacular drone light show, where technology, creativity, and precision merged to create an unforgettable experience.',
    content: `<h2>Technological Exhibition</h2>
<p>The skies above Ahmedabad Science City came alive with a spectacular drone light show, where technology, creativity, and precision merged to create an unforgettable experience.</p>`,
    thumbnailUrl: '/stories/science-city-drones-show/thumbnail.png',
    coverImageUrl: '/stories/science-city-drones-show/thumbnail.png',
    videoUrl: '/stories/3fXIKCCdkWQLC4ZtpBCZ/video.mp4',
    instagramUrl: '',
    metaTitle: 'Science City Drone Show Ahmedabad | FLYBIT Dynamics',
    metaDescription:
      'Spectacular drone light show at Ahmedabad Science City featuring technology, creativity, and precision.',
    seoKeywords: ['science city drone show', 'ahmedabad science city', 'drone show india'],
    tags: ['Government', 'Science City', 'Ahmedabad'],
    author: 'FLYBIT Team',
    readingTime: '3 min',
    featured: false,
    status: 'published',
    views: 3120,
    createdAt: '2025-02-03T10:00:00.000Z',
    updatedAt: '2025-02-03T10:00:00.000Z',
  },
  {
    id: 'n0HrUCdju1Q2chJh1S42',
    title: 'SciKnow Fest',
    slug: 'sciknow-fest',
    showType: 'Social Events',
    shortDescription:
      'At SciKnowTech, we transformed a drone show into an inspiring learning experience, combining technology, storytelling, and innovation to spark curiosity in young minds.',
    content: `<h2>Educational Drone Experience</h2>
<p>At SciKnowTech, we transformed a drone show into an inspiring learning experience, combining technology, storytelling, and innovation to spark curiosity in young minds.</p>`,
    thumbnailUrl: '/stories/sciknow-fest/thumbnail.png',
    coverImageUrl: '/stories/sciknow-fest/thumbnail.png',
    videoUrl: '/stories/science city drones show/video.mp4',
    instagramUrl: '',
    metaTitle: 'SciKnow Fest Drone Show | FLYBIT Dynamics',
    metaDescription:
      'Inspiring learning experience through drone light shows at SciKnow Fest with SciKnowTech.',
    seoKeywords: ['sciknow fest', 'educational drone show', 'sciknowtech'],
    tags: ['Social Events', 'Education', 'Fest'],
    author: 'FLYBIT Team',
    readingTime: '3 min',
    featured: false,
    status: 'published',
    views: 1420,
    createdAt: '2024-11-01T10:00:00.000Z',
    updatedAt: '2024-11-01T10:00:00.000Z',
  },
  {
    id: 'V1SakUWqB5qHXhklphTw',
    title: 'Ram Navmi',
    slug: 'ram-navmi',
    showType: 'Spiritual',
    shortDescription:
      'On the sacred occasion of Ram Navmi, the skies above Science City Ahmedabad came alive with a spectacular drone show celebrating the legacy of Shri Ram.',
    content: `<h2>Spiritual Spectacle</h2>
<p>On the sacred occasion of Ram Navmi, the skies above Science City Ahmedabad came alive with a spectacular drone show celebrating the legacy of Shri Ram.</p>`,
    thumbnailUrl: '/stories/ram-navmi/thumbnail.png',
    coverImageUrl: '/stories/ram-navmi/thumbnail.png',
    videoUrl: '/stories/Ram Navmi/video.mp4',
    instagramUrl: '',
    metaTitle: 'Ram Navmi Spiritual Drone Show | FLYBIT Dynamics',
    metaDescription:
      'Sacred Ram Navmi drone light show celebrating the legacy of Shri Ram at Science City Ahmedabad.',
    seoKeywords: ['ram navmi drone show', 'spiritual drone light show', 'shri ram drones'],
    tags: ['Spiritual', 'Ram Navmi', 'Ahmedabad'],
    author: 'FLYBIT Team',
    readingTime: '3 min',
    featured: true,
    status: 'published',
    views: 4890,
    createdAt: '2025-03-01T10:00:00.000Z',
    updatedAt: '2025-03-01T10:00:00.000Z',
  },
  {
    id: 'AO1Z8RQ9AM6JHQp6EySN',
    title: 'Prateek & Jenny Wedding',
    slug: 'prateek-jenny-wedding',
    showType: 'Social Events',
    shortDescription:
      'Prateek & Jeny’s wedding became an unforgettable sky spectacle as a custom drone show transformed their love story into breathtaking aerial art.',
    content: `<h2>Wedding Aerial Art</h2>
<p>Prateek & Jeny’s wedding became an unforgettable sky spectacle as a custom drone show transformed their love story into breathtaking aerial art.</p>`,
    thumbnailUrl: '/stories/prateek-jenny-wedding/thumbnail.png',
    coverImageUrl: '/stories/prateek-jenny-wedding/thumbnail.png',
    videoUrl: '/stories/Prateek wedding/video.mp4',
    instagramUrl: '',
    metaTitle: 'Prateek & Jenny Wedding Drone Show | FLYBIT Dynamics',
    metaDescription:
      'Custom wedding drone show turning Prateek & Jenny’s love story into breathtaking aerial light art.',
    seoKeywords: ['wedding drone show', 'custom wedding drones', 'prateek jenny wedding'],
    tags: ['Social Events', 'Wedding', 'Custom Show'],
    author: 'FLYBIT Team',
    readingTime: '3 min',
    featured: false,
    status: 'published',
    views: 2980,
    createdAt: '2025-03-22T10:00:00.000Z',
    updatedAt: '2025-03-22T10:00:00.000Z',
  },
  {
    id: 'Zd7nGPrFQYPGLtU3njiS',
    title: 'khodiyar ma temple ( kkv )',
    slug: 'khodiyar-ma-temple-kkv',
    showType: 'Spiritual',
    shortDescription:
      'Witnessing devotion take flight at Khodiyar Maa Temple, KKV Dham. Through a mesmerizing drone show, faith and technology came together to create an unforgettable spiritual experience in the skies above Ahmedabad.',
    content: `<h2>Devotion in the Skies</h2>
<p>Witnessing devotion take flight at Khodiyar Maa Temple, KKV Dham. Through a mesmerizing drone show, faith and technology came together to create an unforgettable spiritual experience in the skies above Ahmedabad.</p>`,
    thumbnailUrl: '/stories/khodiyar-ma-temple-kkv/thumbnail.png',
    coverImageUrl: '/stories/khodiyar-ma-temple-kkv/thumbnail.png',
    videoUrl: '/stories/khodiyar ma temple ( kkv )/video.mp4',
    instagramUrl: '',
    metaTitle: 'Khodiyar Ma Temple Drone Show | FLYBIT Dynamics',
    metaDescription:
      'Devotional drone light show at Khodiyar Maa Temple KKV Dham uniting faith and technology.',
    seoKeywords: ['khodiyar ma temple', 'kkv dham', 'devotional drone show'],
    tags: ['Spiritual', 'Temple', 'Devotion'],
    author: 'FLYBIT Team',
    readingTime: '3 min',
    featured: false,
    status: 'published',
    views: 3410,
    createdAt: '2025-02-15T10:00:00.000Z',
    updatedAt: '2025-02-15T10:00:00.000Z',
  },
  {
    id: 'peiPa6iVL3irXCVrKDNQ',
    title: 'Het & Rucha Wedding',
    slug: 'wedding',
    showType: 'Social Events',
    shortDescription:
      'A magical drone light show illuminated the night sky, turning their wedding celebration into an unforgettable experience filled with wonder and joy.',
    content: `<h2>Magical Wedding Finale</h2>
<p>A magical drone light show illuminated the night sky, turning their wedding celebration into an unforgettable experience filled with wonder and joy.</p>`,
    thumbnailUrl: '/stories/wedding/thumbnail.png',
    coverImageUrl: '/stories/wedding/thumbnail.png',
    videoUrl: '/stories/Het & Rucha Wedding/video.mp4',
    instagramUrl: '',
    metaTitle: 'Het & Rucha Wedding Drone Light Show | FLYBIT',
    metaDescription:
      'A magical drone light show illuminating the night sky for Het & Rucha’s wedding celebration.',
    seoKeywords: ['het rucha wedding', 'wedding drone light show', 'luxury wedding drones'],
    tags: ['Social Events', 'Wedding', 'Celebration'],
    author: 'FLYBIT Team',
    readingTime: '3 min',
    featured: true,
    status: 'published',
    views: 4120,
    createdAt: '2025-01-10T10:00:00.000Z',
    updatedAt: '2025-01-10T10:00:00.000Z',
  },
  {
    id: 'Cb1YHJMLLjm6XMmoOZpx',
    title: 'Hanuman Jayanti',
    slug: 'hanuman-jayanti',
    showType: 'Spiritual',
    shortDescription:
      'At Royal Rivaz Farm, Hanuman Jayanti lit up the sky with a breathtaking drone show by Flybit Dynamics. Lord Hanuman’s divine form came alive among the stars, blending devotion, technology, and unforgettable emotions into one magical experience.',
    content: `<h2>Divine Aerial Illumination</h2>
<p>At Royal Rivaz Farm, Hanuman Jayanti lit up the sky with a breathtaking drone show by Flybit Dynamics. Lord Hanuman’s divine form came alive among the stars, blending devotion, technology, and unforgettable emotions into one magical experience.</p>`,
    thumbnailUrl: '/stories/hanuman-jayanti/thumbnail.png',
    coverImageUrl: '/stories/hanuman-jayanti/thumbnail.png',
    videoUrl: '/stories/Hanuman Jayanti/video.mp4',
    instagramUrl: '',
    metaTitle: 'Hanuman Jayanti Drone Show Royal Rivaz | FLYBIT',
    metaDescription:
      'Lord Hanuman’s divine form brought to life among the stars at Royal Rivaz Farm during Hanuman Jayanti.',
    seoKeywords: ['hanuman jayanti drone show', 'royal rivaz farm', 'spiritual drones'],
    tags: ['Spiritual', 'Hanuman Jayanti', 'Royal Rivaz'],
    author: 'FLYBIT Team',
    readingTime: '3 min',
    featured: false,
    status: 'published',
    views: 3780,
    createdAt: '2025-03-25T10:00:00.000Z',
    updatedAt: '2025-03-25T10:00:00.000Z',
  },
  {
    id: 'mwSAWYi49Z8wt2YBK7SB',
    title: 'DGP Cup 2026',
    slug: 'dgp-cup-2026',
    showType: 'Sports & Entertainment',
    shortDescription:
      'Client/Event: Gujarat Police – DGP Cup 2026 Location: Gujarat, India Objective: Create a high-impact, patriotic, and memorable opening/closing ceremony',
    content: `<h2>Patriotic Sports Ceremony</h2>
<p>Client/Event: Gujarat Police – DGP Cup 2026 Location: Gujarat, India Objective: Create a high-impact, patriotic, and memorable opening/closing ceremony through a precision drone formation show.</p>`,
    thumbnailUrl: '/stories/dgp-cup-2026/thumbnail.png',
    coverImageUrl: '/stories/dgp-cup-2026/thumbnail.png',
    videoUrl: '/stories/DGP Cup 2026/video.mp4',
    instagramUrl: '',
    metaTitle: 'Gujarat Police DGP Cup 2026 Drone Show | FLYBIT',
    metaDescription:
      'High-impact patriotic opening ceremony drone show for Gujarat Police DGP Cup 2026.',
    seoKeywords: ['dgp cup 2026', 'gujarat police drone show', 'sports opening ceremony'],
    tags: ['Sports & Entertainment', 'Gujarat Police', 'DGP Cup'],
    author: 'FLYBIT Team',
    readingTime: '3 min',
    featured: false,
    status: 'published',
    views: 2650,
    createdAt: '2026-02-01T10:00:00.000Z',
    updatedAt: '2026-02-01T10:00:00.000Z',
  },
  {
    id: 'k0E2GuU9pzfJDJkPKKRd',
    title: 'amrut-vandana',
    slug: 'amrut-vandana',
    showType: 'Spiritual',
    shortDescription:
      'Celebrating the launch of AmrutVandana, a book on Pujya Shri Madhavpriyadasji Swami, organized by SGVP — illuminated through a divine drone light show by Flybit Dynamics. The event was graced by the presence of the Hon’ble CM of Gujarat.',
    content: `<h2>Divine Book Launch</h2>
<p>Celebrating the launch of AmrutVandana, a book on Pujya Shri Madhavpriyadasji Swami, organized by SGVP — illuminated through a divine drone light show by Flybit Dynamics. The event was graced by the presence of the Hon’ble CM of Gujarat.</p>`,
    thumbnailUrl: '/stories/amrut-vandana/thumbnail.png',
    coverImageUrl: '/stories/amrut-vandana/thumbnail.png',
    videoUrl: '/stories/amrut-vandana/video.mp4',
    instagramUrl: '',
    metaTitle: 'AmrutVandana SGVP Drone Light Show | FLYBIT Dynamics',
    metaDescription:
      'Divine drone light show celebrating the launch of AmrutVandana by SGVP in the presence of the Hon’ble CM of Gujarat.',
    seoKeywords: ['amrut vandana', 'sgvp drone show', 'cm of gujarat event'],
    tags: ['Spiritual', 'SGVP', 'AmrutVandana'],
    author: 'FLYBIT Team',
    readingTime: '3 min',
    featured: true,
    status: 'published',
    views: 5210,
    createdAt: '2025-02-28T10:00:00.000Z',
    updatedAt: '2025-02-28T10:00:00.000Z',
  },
];
